version: '3.6'
services:
  gabot:
    build:
      context: ./gabot
    container_name: gabot_slackconnector
    environment:
      - MONGO_HOST=database
    depends_on:
      - database
  database:
    image: mongo
    container_name: gabot_mongo
    environment:
      - MONGO_INITDB_DATABASE=gabot
    volumes:
      - ./mongodata:/data/db
    ports:
      - '27017-27019:27017-27019'
