version: '3.6'
services:
  rabbitmq:
   image: rabbitmq:3-management
   ports:
      # The standard AMQP protocol port
      - '5672:5672'
      # HTTP management UI
      - '15672:15672'
   networks:
      - network
   container_name: rabbitmq
   restart: 'always'

  gabot_wikipedia_search:
   build:
      context: ./gabot_wikipedia_search
   container_name: gabot_wikipedia_search
   networks:
      - network
   environment:
      - RABBITMQ_HOST=rabbitmq
   depends_on:
      - rabbitmq

  gabot_slack_writer:
   build:
      context: ./gabot_slack_writer
   container_name: gabot_slack_writer
   networks:
      - network
   environment:
      - RABBITMQ_HOST=rabbitmq
   depends_on:
      - rabbitmq

  gabot_slack_reader_2:
   build:
     context: ./gabot_slack_reader_2
   container_name: gabot_slack_reader_2
   ports:
      - 3000:3000
   environment:
      - RABBITMQ_HOST=rabbitmq
   depends_on:
      - rabbitmq
   networks:
      - network
networks:
  network: {}
